# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe48e8d6de8cecba047d15c9ba77a06f53f52f14eb773acbbe104ea8a6bfe0bb41798474a7341eb8560bd0c7191ed98a0d05dc78d7fa4c40dea929e4cf1989e3

test:
  secret_key_base: 6a3a1899c9d4fae0ee2bf9fcb656b1471894f4dfbf24266899aadb0efb26addd224a3e700dab58505417e79c7274c549b9ab077cd72d00d76fca0051a95bec73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
